---
dependency:
  name: galaxy
  options:
    role-name-check: 0  # Отключаем проверку имени

driver:
  name: docker  # Меняем на docker (проще чем podman)

platforms:
  - name: instance
    image: ubuntu:22.04

provisioner:
  name: ansible

verifier:
  name: ansible
