---
- name: Verify
  hosts: all
  tasks:
    - name: Check Vector user exists
      shell: "id vector"
      register: vector_user
      changed_when: false
    
    - name: Check Vector directories
      stat:
        path: "{{ item }}"
      loop:
        - /etc/vector
        - /var/lib/vector
      register: dirs
    
    - name: Display verification results
      debug:
        msg: "Vector infrastructure ready on {{ ansible_distribution }}"
