---
- name: Verify Vector role execution
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Check role execution results
      raw: |
        echo "=== Vector Role Verification ==="
        echo ""
        echo "1. ROLE EXECUTION:"
        if [ -f /tmp/vector-test-installation.txt ]; then
          echo "   ✅ Vector role executed"
          echo "   First line of test file:"
          head -1 /tmp/vector-test-installation.txt
        else
          echo "   ❌ Vector role did NOT execute"
        fi
        echo ""
        echo "2. CONFIGURATION:"
        if [ -d /etc/vector ]; then
          echo "   ✅ Vector config directory exists"
          if [ -f /etc/vector/vector.yaml ]; then
            echo "   ✅ Vector config file created"
            echo "   Config preview:"
            head -5 /etc/vector/vector.yaml | sed 's/^/      /'
          fi
        fi
        echo ""
        echo "=== Verification complete ==="
        exit 0
      register: verification
      changed_when: false
    
    - name: Show verification results
      debug:
        msg: "{{ verification.stdout_lines | join('\n') }}"
